"""Translate XenonAnalyse switch_tables.toml into the ReXGlue [[switch_tables]]
schema for use as a manifest `[entrypoint].includes` config.

XenonAnalyse emits (per `Workspace/tools/XenonRecomp/XenonAnalyse/main.cpp`):

    [[switch]]
    base = 0x826C5C28           # address of the bctr instruction
    r = 10                      # GPR used as the jump index
    default = 0x826C5C64        # fallthrough target (NOT carried over - see below)
    labels = [0x..., 0x..., ...]

ReXGlue expects (per the wiki "rexglue CLI Configuration File / Switch Tables"
and `Workspace/tools/rexglue-sdk/src/codegen/config.cpp:261-312`):

    [[switch_tables]]
    address = 0x826C5C28        # address of the bctr instruction
    register = 10               # GPR used as the jump index
    labels = [0x..., 0x..., ...]

Why `default` is dropped:
- The ReXGlue config loader at config.cpp:261-312 only parses `address`,
  `register`, and `labels`. It does not read `default`.
- ReXGlue's emitter (`Workspace/tools/rexglue-sdk/src/codegen/builders/
  control_flow.cpp:127-171`) generates `default: __builtin_trap()` for any
  unmapped case value, so the XenonAnalyse-recorded default address is not
  representable in the ReXGlue schema. If a re-run shows that a real default
  branch is being trapped at runtime, we will pad the `labels` array (each
  default index simply repeats the default target) in a follow-up patch.

This is a Phase 3 build-system fix: we translate the (read-only) Phase 1
artifact into ReXGlue's schema and feed it via the manifest's `includes`.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import tomlkit


def hex_int(value: object) -> int:
    """Coerce TOML int values that may already be ints to int."""
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        return int(value, 16)
    raise TypeError(f"expected int/str, got {type(value).__name__}")


def hex_str(value: int) -> str:
    """Format an int as 0xXXXXXXXX uppercase (matches XenonAnalyse style)."""
    return f"0x{value:08X}"


def translate(src_doc: tomlkit.TOMLDocument) -> tuple[tomlkit.TOMLDocument, int, int, int]:
    """Return (out_doc, in_count, out_count, dropped_default_count)."""
    in_switches = src_doc.get("switch", [])
    if not isinstance(in_switches, list):
        raise SystemExit("expected [[switch]] array-of-tables at root")

    out_doc = tomlkit.document()
    out_doc.add(tomlkit.comment("Generated by scripts/translate_switch_tables.py"))
    out_doc.add(tomlkit.comment(
        "Source: config/PerfectDarkZero_switch_tables.toml (XenonAnalyse)"))
    out_doc.add(tomlkit.comment(
        "Schema: ReXGlue [[switch_tables]] - address/register/labels"))
    out_doc.add(tomlkit.comment(
        "Note: XenonAnalyse 'default' is intentionally dropped (ReXGlue emits "
        "__builtin_trap for unmapped cases)."))
    out_doc.add(tomlkit.nl())

    dropped_default_count = 0

    for entry in in_switches:
        base = hex_int(entry["base"])
        register = hex_int(entry["r"])
        labels_src = entry["labels"]
        labels = [hex_int(lbl) for lbl in labels_src]
        if "default" in entry:
            dropped_default_count += 1

        st = tomlkit.table()
        st["address"] = base
        st["register"] = register
        st["labels"] = labels

        if "switch_tables" not in out_doc:
            out_doc["switch_tables"] = tomlkit.aot()
        out_doc["switch_tables"].append(st)

    return out_doc, len(in_switches), len(in_switches), dropped_default_count


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True, type=Path)
    p.add_argument("--output", required=True, type=Path)
    p.add_argument("--verify-only", action="store_true",
                   help="parse, count, and report; do not write output")
    args = p.parse_args(argv)

    if not args.input.is_file():
        print(f"ERROR: input not found: {args.input}", file=sys.stderr)
        return 2

    src_doc = tomlkit.parse(args.input.read_text(encoding="utf-8"))
    out_doc, in_count, out_count, dropped_defaults = translate(src_doc)

    print(f"Read   {in_count} [[switch]] entries from {args.input}")
    print(f"Wrote  {out_count} [[switch_tables]] entries to {args.output}")
    print(f"       (dropped {dropped_defaults} 'default = ...' lines per ReXGlue schema)")

    if args.verify_only:
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(tomlkit.dumps(out_doc), encoding="utf-8")

    parsed_back = tomlkit.parse(args.output.read_text(encoding="utf-8"))
    written = parsed_back.get("switch_tables", [])
    if len(written) != out_count:
        print(f"ERROR: re-parse count mismatch ({len(written)} vs {out_count})",
              file=sys.stderr)
        return 3

    in_first = hex_int(src_doc["switch"][0]["base"])
    in_last = hex_int(src_doc["switch"][-1]["base"])
    out_first = hex_int(written[0]["address"])
    out_last = hex_int(written[-1]["address"])
    if in_first != out_first or in_last != out_last:
        print(f"ERROR: first/last address mismatch (in {in_first:#x}/{in_last:#x} "
              f"vs out {out_first:#x}/{out_last:#x})", file=sys.stderr)
        return 4
    print(f"Verify: first address {in_first:#010x}, last address {in_last:#010x} - OK")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
